# change the followings to match your Github username and repo name
# baseurl: "" # the name of your github repo
url: "https://adedamola-adesokan.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Adedamola Adesokan Personal Website"
description: This is the website for Adedamola Adesokan

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Adedamola Adesokan
author-bio: Senior Cybersecurity Engineer with a robust background in application security, vulnerability assessment, penetration testing, GRC and cloud security. Proven expertise in implementing security protocols and managing cybersecurity projects across various industries to align with business objectives.  # change to false to hide
author-image: Image.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Certifications
  permalink: certifications
- text: Publications
  permalink: publications

# use false to turn off any social media links
# twitter: https://twitter.com/
# facebook: https://facebook.com/
# instagram: https://instagram.com/
github: https://github.com/adedamola-adesokan/
linkedin: https://linkedin.com/adedamola-adesokan/ 
medium: false
google-scholar: https://scholar.google.com/citations?user=kmaNZ5IAAAAJ&hl=en
email: adesokanphilip74@unm.edu

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
