# change the followings to match your Github username and repo name
# baseurl: "" # the name of your github repo
url: "https://adedamola-adesokan.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Adedamola Adesokan Personal Website"
description: This is the website for Adedamola Adesokan

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Adedamola Adesokan
author-bio: PhD | Research and Development | Cybersecurity | CISSP | Cloud Engineering | DevSecOps | AppSec # change to false to hide
author-image: Image.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Certifications
  permalink: certifications
- text: Publications
  permalink: publications
- text: Education
  permalink: education
- text: Honors and Awards
  permalink: honors_and_awards

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/adedamola-adesokan/
linkedin: https://linkedin.com/adedamola-adesokan/ 
medium: false
google-scholar: https://scholar.google.com/citations?user=kmaNZ5IAAAAJ&hl=en
email: adesokanphilip74@unm.edu

# # footer information
# footer-msg: "Powered by Tailpages"
# footer-msg-link: https://github.com/harrywang/tailpages

# # google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
